name: Test workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          echo "Running tests..."
          echo "Tests complete"
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Run app
        run: npm test
      - uses: actions/upload-artifact@v3
        with:
          path: piesek.json
          key: piesek
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          echo "pwd"
          pwd
          echo "ls"
          ls -la
          echo Deploy
