name: Test workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Running tests..."
          sleep 10
          echo "Tests complete"
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Run app
        run: npm start
