name: Test workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          echo "Running tests..."
          echo "Tests complete"
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Run app
        run: npm start
      - name: Create dummy file
        run: |
          touch dummy.txt
          echo pwd
          pwd
          echo ls
          ls -la
      - uses: actions/cache@v3
        with:
          path: dummy.txt
          key: piesek
      - name: Upload dummy file
        uses: actions/upload-artifact@v2
        with:
          name: dummy
          path: dummy.txt
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: dummy.txt
          key: piesek
      - name: Deploy
        run: |
          echo "pwd"
          pwd
          echo "ls"
          ls -la
          echo Deploy
